{
    'name': 'Theme Mars',
    'description': 'Theme Mars is an attractive and modern Website theme',
    'summary': 'Theme Mars is a new kind of Theme. '
               'The theme is a very user-friendly and is suitable for your website.',
    'category': 'Theme',
    'version': '16.0.1.0.0',
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'depends': ['base', 'website', 'website_sale', 'portal', 'website_blog'],
    'data': [
        # 'views/blog.xml',//unwanted file
        # 'views/website_blog_views.xml',
        # 'views/blog_sidebar_right.xml',
        # 'views/blog_sidebar.xml',
        # 'views/dynamic_blog.xml',
        # 'views/blog_sidebar_left.xml',
        # 'views/sidebar_left_sticky.xml',
        # 'views/sidebar_right_sticky.xml',
        # 'views/tags.xml',
        'views/theme_snippe'
        't.xml',
        'views/page_404.xml',
        'views/thumbnail.xml',
        'views/about.xml',
        'views/services.xml',
        'views/client.xml',
        'views/team.xml',
        'views/banner.xml',
        # 'views/blogs.xml',
        'views/counter.xml',
        'views/mars_blog.xml',
        # 'views/demo.xml',
        # 'views/sidebar.xml',
        'views/contact_bottom_map_snippets.xml',
        'views/contact_full_screen_map.xml',
        'views/contact_full_width_map.xml',
        # 'views/contact_sidebar_left.xml',
        # 'views/contact_sidebar_right.xml',
        # 'views/contact.xml',
        'views/theme_template_header.xml',
        'views/theme_template_footer.xml',
        'views/layouts.xml',
        'views/theme_template_about.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            "theme_mars/static/src/css/style.css",
            "theme_mars/static/src/css/owl.carousel.min.css",
            "theme_mars/static/src/css/animate.min.css",
            "theme_mars/static/src/css/bootstrap-dropdownhover.min.css",
            "theme_mars/static/src/css/loaders.min.css",
            # "theme_mars/static/src/js/blog.js",
            "/theme_mars/static/src/js/owl.carousel.js",
            "/theme_mars/static/src/js/jquery.appear.min.js",
            "/theme_mars/static/src/js/jquery.easypiechart.min.js",
            # "theme_mars/static/src/js/index.js",
            # "/theme_mars/static/src/js/bootstrap.min.js",
            # "/theme_mars/static/src/js/jquery-2.2.4.min.js",
            "/theme_mars/static/src/js/about_basic2.js",
            "/theme_mars/static/src/js/location.js",
            "/theme_mars/static/src/js/options.js",
            # "/theme_mars/static/src/js/counter_options.js",
            "theme_mars/static/src/js/owl.carousel.min.js",
            "theme_mars/static/src/xml/blog_comments.xml",
            "theme_mars/static/src/xml/blog.xml",
            # "theme_mars/static/src/Images/partners/p (1).png",
            'https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js'
        ],

        # 'website.assets_wysiwyg': [
        #     "/theme_mars/static/src/js/counter_options.js",
        # ]
    },
    # 'images': [
    #     'static/src/Images/partners/p (1).png',
    #     'static/src/Images/team/team (3).jpg',
    #     # 'static/description/theme_screenshot.png',
    # ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
